### ISSUE TITLE
Error with package did_multiplegt_dyn

### ISSUE THREAD

**Issue by teodora-margaritova** [chaisemartinPackages/did_multiplegt_dyn#16]
Hello, 
I would like to first thank you for the excellent paper and package. 
I am estimating a diff-in-diff with non-absorbing treatment, and I have included lag(treatment) as a control, because of reverse causality concerns in my research design. 
I got the following error and was wondering if you could help me out with it: Error in get(paste0("coefs_sq_", l, "_XX")) : 
  object 'coefs_sq_1_XX' not found. 

Here is my code for reference:
r1<-summary(did_multiplegt_dyn(
  df = pt,
  outcome = "PR",
  group = "Unit",
  time = "Year",
  treatment = "Tr",
  controls="Tr_Lag1",
))
r1

**Comment by chaisemartinPackages** [comment]
[This issue was closed in a private email exchange with the OP. However, we report the last suggestion just in case other users have the same issue.] 

Context: **Panel with outcome observed less frequently than the treatment**

Dear Teodora,
Your original data is a balanced panel, where the treatment is observed every period and the outcome is observed every $n$ periods. 
In cases like these, you can use the solution listed in the FAQ of did_multiplegt_dyn for cases where the outcome is observed less frequently than the treatment. You can read below the section I am referring to:

![image](https://github.com/chaisemartinPackages/did_multiplegt_dyn/assets/125619230/102b4e31-edf1-4d01-9a8f-0d485f0922ac)

In a few words, keep your original dataset as it is, with the all the periods you have, even if the outcome variable is missing. Generate the subsets as described above and run the command keeping (g,t) cells that have not switched yet or that have already switched and their first switch happened $n-1$, $n-2$, ..., $2$, $1$ periods before or on a year with non-missing outcome, depending on the subset you are using. Obviously, this method comes with a slight change of interpretation of the combined effects (as explained in the FAQ).
I hope this helps!
Best,
Diego
