### ISSUE TITLE
The optimal number of dynamic effects and placebos

### ISSUE THREAD

**Issue by watsonsuuii** [chaisemartinPackages/did_multiplegt_dyn#25]
I am evaluating the effect of a treatment in a study. However, I want to know how the number of dynamic effects and placebos are suitable for the estimation is determined. I want to know if there is a way of calculating the optimal numbers. I am new to this so kindly pardon me. I would be very grateful to receive a positive response from you.
I look forward to hearing from you.

**Comment by chaisemartinPackages** [comment]
Regarding the number of dynamic effects, there is no clear answer to what you should do, this depends on your application and your assessment of how many periods you think it takes for your treatment to have an effect and how many periods you think this effect will be active or might change. In general, we think (unless you have an extremely large number of periods available) you would want to estimate dynamic effects for as many periods as possible with your data unless you have a strong reason to not do so (or maybe if you have an unbalanced panel or variation in the treatment timing you might want to exclude some of the last effects as the sample on which those can be estimated will get very small). For the placebos, there is the rule of thumb that you always want to estimate as many placebos as you estimate dynamic effects. This is because with the placebo estimates you want to confirm that the outcome of interest would have evolved similarly between treatment and control in the absence of the treatment (parallel trends assumption) and the argument is that if you want to estimate let's say 10 dynamic effects you also want to have 10 insignificant placebo estimates to support your claim that parallel trends hold for 10 periods.
