### ISSUE TITLE
coefficient/SE for controls 

### ISSUE THREAD

**Issue by jiehanL** [chaisemartinPackages/did_multiplegt_dyn#81]
Hi all,

Thank you for developing this amazing package! I’m wondering if it’s possible to pull the coefficients and standard errors for the control variables using the R package did_multiplegt_dyn. If so, could you please guide me on the correct way to do it?

Thank you!

**Comment by LuigiBiagini** [comment]
This is a very good request. Is it possible to include even the R2?

**Comment by chaisemartinPackages** [comment]
Dear Jiehan and Luigi,

Thank you for your question. The package is actually not designed to estimate covariates' regression coefficients and there is no way to pull them, same for the R2 :)

Control variables allow to control for time-varying covariates that may help in obtaining a satisfying (more credible) conditional parallel trend assumptions. See extension 3.5 of [de Chaisemartin et D’Haultfœuille 2024](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3751060). 

If you were to really need to replicate the command's internal operations and those estimates, you would need to estimate the following : 
Within the subset of stayers, for each period, you should regress the outcome first-difference on the covariates first-difference with an intercept to capture the time FE. Then, in order to get interpretable coefficients, you could aggregate those estimates by taking an average weighted by the number of observations used for each estimation. As you see, this would only help to check how the covariates are internally used but would not really have any interpretability. 

As for the R2, since a DID is not a prediction exercice, there is no really interpretable sense to give to a R2, but I guess a classic TWFE would give you that. 

Hope this helps,
Romain
