### ISSUE TITLE
 Control Variables Specification in did_multiplegt_dyn 

### ISSUE THREAD

**Issue by LuJiangYun** [chaisemartinPackages/did_multiplegt_dyn#85]
I am currently utilizing the did_multiplegt_dyn command you developed for a difference-in-differences analysis and have encountered a technical issue regarding how to handle the interaction effects of time-invariant variables with time dummies.

Specifically, I am analyzing the impact of certain policies and am attempting to control for initial values of specific city indicators, such as per capita GDP and city size in the first year of my data period, within the controls() option. However, whether I include initial value controls, initial values * year dummies, or variables that change yearly (such as specific annual per capita GDP), the regression results remain identical to those without any controls(). The results only differ when I generate Xg,t=X_initial*T, controlling for time-invariant controls * year.

I noted that the command documentation mentions the possibility of controlling for the interaction of time-invariant control variables with time trends, but it does not specify how to handle interactions with year dummies. Therefore, I kindly ask if you could help clarify a few points:

1.Does the did_multiplegt_dyn command support including interaction terms between control variables and time dummies in the model?
2.If so, how should I correctly specify these interactions to ensure they are correctly recognized and utilized by the model?
3.If not, do you have any recommended methods or alternative commands to address this limitation?
Thank you very much for your assistance.

**Comment by chaisemartinPackages** [comment]
Dear Jiang Yun,

Thank you for your question. This specific point is not directly treated in the helpfile of the command.

There exists 3 options to control for differential evolutions across groups : 
- _controls_ : as you mentioned this accounts for time-varying covariates only (dummies don't work with it)
- _trends_lin_ : accounts for group-specific linear trends (this does the trick for you if you assume trends are linear)
- _trends_nonparam_ : interacts each value of the support of X with time dummies (this is exactly what you want)

If your initial distribution of X_initial has finite support you should use _trends_nonparam_(X_initial). If not, you can discretize it. I can refer you to the documentation [here](https://drive.google.com/file/d/1NGgScujLCCS4RrwdN-PC1SnVigfBa32h/view) (section 2.3) to learn more about the new parallel trends assumption you have to make in this case. You need a discrete support because you need to have treated and untreated units within values of X_init.

An other case you might have is including X_init-specific linear trends. In this case, indeed you need to include in controls Xg,t=X_initial*T as you mentioned but this is not the same as having dummies for each year. 

Hope this helps,
Romain
