### ISSUE TITLE
factor variables as control?

### ISSUE THREAD

**Issue by xbrown1992** [chaisemartinPackages/did_multiplegt_dyn#88]
Hello 
I really want to include factor variables in my control. How can I do that? I really need (i.education, i.mother's education and i.facther's education) in my control. But it ran into the error- factor-variable and time-series operators not allowed.
Appreciate any help here. Thank you so much

**Comment by chaisemartinPackages** [comment]
Hi,

The error derives from the fact that the _controls( )_ option of the command only takes numerical values. 

Including dummies as you suggest would not work and would anyways not change the results since those effects are already captured in the groups fixed-effects. This is because the dummies you propose are time-invariant. The _controls( )_ option is meant to account for time-varying covariates that strengthen the parallel-trends assumption. 

I invite you to have a closer look at the command's options and #85. 

Hope this helps,
Romain
