### ISSUE TITLE
R package feature request: add Gentzkow data and show how to replicate Chaisemartin & Haultfeuille 2020?

### ISSUE THREAD

**Issue by MatthieuStigler** [chaisemartinPackages/did_multiplegt_dyn#91]
Would it be possible to include the Gentzkow dataset used in Chaisemartin & Haultfeuille 2020 in the package, and show how to replicate their result on page 2984?

I tried with a version of the Gentzkow dataset found elsewhere, but was not able to add the state-year fxed effects (cf #90 )... currently I am getting `0.005705122` while the paper reports 0.0043?

Thanks! 

``` r
library(DIDmultiplegt)

if(!require(multiDiff)) remotes::install_github("MatthieuStigler/multiDiff", upgrade = "never")
#> Loading required package: multiDiff
data(GentzkowData)

DiDM <- did_multiplegt(mode = "old", GentzkowData, Y="prestout", G="cnty90", T="year", D="numdailies")
DiDM$effect
#>   treatment 
#> 0.005705122
```

<sup>Created on 2024-10-14 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by chaisemartinPackages** [comment]
Dear Matthieu,

Thank you for this question. 
Actually there are a few differences that prevent you from getting the same result. 

First, indeed the _trends_nonparam_ option runs into trouble with the old version of the command. We discontinued this package so there is no fix for that (with this command). 
Second, _did_multiplegt_ allows for dynamic effects, which are ruled out in the AER application. Therefore, to replicate the results, you should use the Stata code of our _did_multiplegt_stat_ command that estimates static treatment effects. To include state-year FE you should input the state variable in the _controls_ option. 
Third, there are some preliminary data processing steps in the replication file, but I guess you performed those already. 

We will see if we can include this example with the _stat_ command since it resonates well with the rest of the papers. Thank you for the suggestion. Let us know if you don't get the same results !

Hope this helps,
Romain

**Comment by MatthieuStigler** [comment]
Hi Romain

Thanks a lot for your fast and comprehensive response! Unfortunately, I don't use Stata, and my understanding is that the `did_multiplegt_dyn()` command doesn't nest the AER estimator, i.e. you can get the equivalent of the DiDM estimator with `did_multiplegt_dyn()`?

Thanks!

**Comment by chaisemartinPackages** [comment]
Hi,
Sorry for the delay. 

Actually no since many units switch several times. The dyn command only allows to switch once from the baseline. As it stands, to the best of my knowledge, only the stat command would allow to replicate this. 
If you really cannot use Stata, you can use the preliminary-beta version in R that is in the repository but it does not allow for controls yet... We aim at releasing a version with controls soon :)

Best,
Romain
