### ISSUE TITLE
Can I specify `setDTthreads()` to reduce estimation time?

### ISSUE THREAD

**Issue by jcvdav** [chaisemartinPackages/did_multiplegt_dyn#99]
The package has no issues. I am mostly wondering if, off the top of your head, there is anything I can do to speed-up estimation.

For context, I have data set with 9,805,620 observations, corresponding to a balanced panel of 2,685 groups and 3,652 time periods. Many groups are treated more than once. I am running this through the R package on a descent MBP with an Apple M4 max (16-core), and estimation takes a couple of hours. Note that this data are already a subset of the full data set with which I want to perform the full analysis, I am just exploring at this point.

I see `data.table` is already being used, and I know that when `data.table` is loaded it uses 50% of threads by default (here, 8). I could not find any place in the code of `did_multiplegt_dyn` where `setDTthreads` was called, or an option to specify it. I have two questions:
1) Will me manually specifying `setDTthreads(threads = 14)` be overruled by any other defaults in your code?
2) If doing this does not interfere with your code, would it be worth exploring the idea of allowing users to pass this parameter to `did_multiplegt_dyn()` or at least including a mention of it in the documentation's FAQ section?

**Comment by chaisemartinPackages** [comment]
Dear user,

I am Romain from the team. 

To the best of my knowledge, there is nothing in our code that prevents you from manipulating those parameters. Let me know if it does not work. 

One manual thing you may do to improve estimation time is to drop observations that will be removed anyways. This may allow the command to not have to manipulate the entire dataset all the time. In particular, you can remove observations K lags after their first treatment if you estimate K lagged effects. Since you have a long panel, arguably, you will have many units that were already treated and therefore do not serve as controls nor contribute to the estimation anymore. (This advice relies on your treatment being binary staggered. Note that if units are treated several times, only the first treatment _change_ will be considered a switch in the estimation.)

Hope this helps,
Romain

**Comment by jcvdav** [comment]
Hi Romain - Thank you, this response is helpful. I'll increase the number of threads available.
